spring:
  application:
    name: backend

  security:
    user:
      name: admin  # hardcoded skal fixes
      password: adminpassword  # hardcoded skal fixes

#  security:
#    user:
#      name: ${SPRING_SECURITY_USER_NAME}
#      password: ${SPRING_SECURITY_USER_PASSWORD}

  datasource:
    url: jdbc:postgresql://localhost:5432/db # NAME MUST NOT CHANGE
    username: dev
    password: kage

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

# SÃ¦tter en global base path for hele applikationen
server:
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: DEBUG